package servlets;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/test")
public class test extends HttpServlet {
	private static final long serialVersionUID = 1L;
       

	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
	
		PrintWriter out=response.getWriter();
		out.println("<!DOCTYPE html>\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"UTF-8\">\r\n"
				+ "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "  <link rel=\"stylesheet\" href=\"styles.css\">\r\n"
				+ "  <script src=\"https://kit.fontawesome.com/11bc3c9fe9.js\" crossorigin=\"anonymous\"></script>\r\n"
				+ "  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n"
				+ "  <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n"
				+ "  <title>Document</title>\r\n"
				+ "  <style type=\"text/css\">\r\n"
				+ "\r\n"
				+ "@import url(https://fonts.googleapis.com/css?family=Open+Sans);\r\n"
				+ "\r\n"
				+ ".box{\r\n"
				+ "  \r\n"
				+ "  font-family: 'Open Sans', sans-serif;\r\n"
				+ "  display:grid;\r\n"
				+ "  place-items:center;\r\n"
				+ " height:30vh;\r\n"
				+ "  background-color:voilet;\r\n"
				+ "      \r\n"
				+ "}\r\n"
				+ "*{\r\n"
				+ "  margin:0;\r\n"
				+ "  padding:0;\r\n"
				+ "}\r\n"
				+ ".container-hold{\r\n"
				+ "  width:30%;\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".search {\r\n"
				+ "  width: 100%;\r\n"
				+ "  position: relative;\r\n"
				+ "  display: flex;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".searchTerm {\r\n"
				+ "  width: 100%;\r\n"
				+ "  border: 3px solid #00B4CC;\r\n"
				+ "  border-right: none;\r\n"
				+ "  padding: 5px;\r\n"
				+ "  height: 50px;\r\n"
				+ "  border-radius: 5px 0 0 5px;\r\n"
				+ "  outline: none;\r\n"
				+ "  color: #9DBFAF;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".searchTerm:focus{\r\n"
				+ "  color: #00B4CC;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".searchButton {\r\n"
				+ "  width: 40px;\r\n"
				+ "  height: 50px;\r\n"
				+ "  border: 1px solid #00B4CC;\r\n"
				+ "  background: #00B4CC;\r\n"
				+ "  text-align: center;\r\n"
				+ "  color: #fff;\r\n"
				+ "  border-radius: 0 5px 5px 0;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  font-size: 20px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".wrap{\r\n"
				+ "  width: 100%;\r\n"
				+ "  margin-bottom:20px;\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "input {\r\n"
				+ "    font-size: 24px;\r\n"
				+ "}\r\n"
				+ "</style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "\r\n"
				+ "  <aside class=\"aside-section\">\r\n"
				+ "    <div class=\"logo-container\">\r\n"
				+ "      <h1 class=\"brand-name\">\r\n"
				+ "        <i class=\"fa-solid fa-book-open-reader\"></i>\r\n"
				+ "        Ineuron Library\r\n"
				+ "      </h1>\r\n"
				+ "       </div>\r\n"
				+ "     <div onclick=\"display('section6')\">  \r\n"
				+ "     <div class=\"nav-button \">\r\n"
				+ "          <p>\r\n"
				+ "            <i class=\"fa-solid fa-book-atlas\"></i>\r\n"
				+ "            search\r\n"
				+ "          </p>\r\n"
				+ "        </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "     <div onclick=\"display('section1')\">\r\n"
				+ "        <div class=\"nav-button \">\r\n"
				+ "          <p>\r\n"
				+ "            <i class=\"fa-solid fa-book-atlas\"></i>\r\n"
				+ "            view\r\n"
				+ "          </p>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    <nav class=\"navigation\">\r\n"
				+ "      <a href=\"issue_book.html\">\r\n"
				+ "        <div class=\"nav-button\" >\r\n"
				+ "          <p>\r\n"
				+ "            <i class='bx bx-cart-add'></i>\r\n"
				+ "            Issue Book\r\n"
				+ "          </p>\r\n"
				+ "        </div>\r\n"
				+ "      </a>\r\n"
				+ "      <a href=\"return_book.html\">\r\n"
				+ "        <div class=\"nav-button\">\r\n"
				+ "          <p>\r\n"
				+ "            <i class='bx bxs-cart-download'></i>\r\n"
				+ "            return book\r\n"
				+ "          </p>\r\n"
				+ "        </div>\r\n"
				+ "      </a>\r\n"
				+ "      <div onclick=\"display('section3')\">\r\n"
				+ "        <div class=\"nav-button \">\r\n"
				+ "          <p>\r\n"
				+ "            <i class=\"fa-solid fa-book-atlas\"></i>\r\n"
				+ "            manage library\r\n"
				+ "          </p>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "      <div onclick=\"display('section4') \">\r\n"
				+ "        <div class=\"nav-button \">\r\n"
				+ "          <p>\r\n"
				+ "            <i class=\"fa-solid fa-people-roof\"></i>\r\n"
				+ "            manage student\r\n"
				+ "          </p>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "      <div onclick=\"display('section5')\">\r\n"
				+ "        <div class=\"nav-button \">\r\n"
				+ "          <p>\r\n"
				+ "            <i class=\"fa-solid fa-clipboard-user\"></i>\r\n"
				+ "            view issue record\r\n"
				+ "          </p>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "      <div class=\" log-out\">\r\n"
				+ "        <p>\r\n"
				+ "          <a href=\"admin.html\" class=\"log-out-a\"><i class=\"fa-solid fa-right-from-bracket\"></i>\r\n"
				+ "            Log out</a>\r\n"
				+ "        </p>\r\n"
				+ "      </div>\r\n"
				+ "    </nav>\r\n"
				+ "  </aside>\r\n"
				+ "  <div id='section6'> \r\n"
				+ "  <div class='box'>\r\n"
				+ "<h1 style=\"color:#fc6603;\"> Book Search</h1>\r\n"
				+ "<b style=\"font-size:18px\" >Search by Book Name or Author or Subject</b>\r\n"
				+ "<div class='container-hold'>\r\n"
				+ "\r\n"
				+ " <div class=\"wrap\">\r\n"
				+ "\r\n"
				+ "  <form  method=\"get\"  action=\"./search/name\">\r\n"
				+ "    <div class=\"search\">\r\n"
				+ "      <input type=\"text\" required name=\"book name\" class=\"searchTerm\" placeholder=\"search\">\r\n"
				+ "      <button type=\"submit\" class=\"searchButton\">\r\n"
				+ "        <i class=\"fa fa-search\"></i>\r\n"
				+ "     </button>\r\n"
				+ "   </div>\r\n"
				+ "  </form>\r\n"
				+ "</div>\r\n"
				+ "</div>\r\n"
				+ "</div>\r\n"
				+ "</div>\r\n"
				+ "    <div id=\"section1\">\r\n"
				+ "    <div class=\"margin-lt\">\r\n"
				+ "      <div class=\"drop_down\">\r\n"
				+ "        <h1 class=\"header\" style=\"color:#fc6603;\" >view</h1>\r\n"
				+ "        <form method=\"get\" action=\"./view/allstudents\">\r\n"
				+ "        <button type=\"submit\" class=\"btn\" style=\"background-color:green; margin-bottom:20px;\">\r\n"
				+ "        <i class=\"fa-solid fa-cloud-arrow-up\"></i>\r\n"
				+ "            view all students\r\n"
				+ "        </button>\r\n"
				+ "        </form>\r\n"
				+ "         <form method=\"get\" action=\"./view/allbooks\">\r\n"
				+ "        <button type=\"submit\" class=\"btn\" style=\"background-color:green; margin-bottom:20px;\">\r\n"
				+ "        <i class=\"fa-solid fa-cloud-arrow-up\"></i>\r\n"
				+ "            view all Books\r\n"
				+ "        </button>\r\n"
				+ "        </form>\r\n"
				+ "       \r\n"
				+ "        \r\n"
				+ "        </div>\r\n"
				+ "        </div>\r\n"
				+ "        </div>\r\n"
				+ "  <!-- Manage Library  -->\r\n"
				+ "  <div id=\"section3\">\r\n"
				+ "    <div class=\"margin-lt\">\r\n"
				+ "      <div class=\"drop_down\">\r\n"
				+ "        <h1 class=\"header\" style=\"color:#fc6603;\" >Manage Library</h1>\r\n"
				+ "        <a href=\"addbook.html\">\r\n"
				+ "          <h1 style=\"color:#039dfc;\">\r\n"
				+ "            <i class=\"fa-solid fa-cloud-arrow-up\"></i>\r\n"
				+ "            Add\r\n"
				+ "          </h1>\r\n"
				+ "        </a>\r\n"
				+ "        <a href=\"updatebook.html\">\r\n"
				+ "          <h1 style=\"color:#039dfc;\">\r\n"
				+ "            <i class=\"fa-solid fa-file-pen\"></i>\r\n"
				+ "            Update\r\n"
				+ "          </h1>\r\n"
				+ "        </a>\r\n"
				+ "        <a href=\"deletebook.html\">\r\n"
				+ "          <h1 style=\"color:#039dfc;\">\r\n"
				+ "            <i class=\"fa-solid fa-trash-can\"></i>\r\n"
				+ "            Delete\r\n"
				+ "          </h1>\r\n"
				+ "        </a>\r\n"
				+ "        <a href=\"searchbook.html\">\r\n"
				+ "          <h1 style=\"color:#039dfc;\">\r\n"
				+ "            <i class=\"fa-solid fa-magnifying-glass\"></i>\r\n"
				+ "            Search\r\n"
				+ "          </h1>\r\n"
				+ "        </a>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "  <!-- Manage Student -->\r\n"
				+ "  <div id=\"section4\">\r\n"
				+ "    <div class=\"margin-lt\">\r\n"
				+ "      <div class=\"drop_down\">\r\n"
				+ "        <h1 class=\"header\" style=\"color:#fc6603;\" >Manage Student</h1>\r\n"
		
				+ "        <a href=\"updatestudent.html\">\r\n"
				+ "          <h1 style=\"color:#039dfc;\">\r\n"
				+ "            <i class=\"fa-solid fa-file-pen\"></i>\r\n"
				+ "            Update\r\n"
				+ "          </h1>\r\n"
				+ "        </a>\r\n"
				+ "        <a href=\"deletestudent.html\">\r\n"
				+ "          <h1 style=\"color:#039dfc;\">\r\n"
				+ "            <i class=\"fa-solid fa-trash-can\"></i>\r\n"
				+ "            Delete\r\n"
				+ "          </h1>\r\n"
				+ "        </a>\r\n"
				+ "        <a href=\"searchstudent.html\">\r\n"
				+ "          <h1 style=\"color:#039dfc;\">\r\n"
				+ "            <i class=\"fa-solid fa-magnifying-glass\"></i>\r\n"
				+ "            Search\r\n"
				+ "          </h1>\r\n"
				+ "        </a>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "  <!-- Manage Issue Record -->\r\n"
				+ "  <div id=\"section5\">\r\n"
				+ "    <div class=\"margin-lt\">\r\n"
				+ "      <div class=\"drop_down\">\r\n"
				+ "        <h1 class=\"header\" style=\"color:#fc6603;\" ;>View Issue Record</h1>\r\n"
				+ "          <form method=\"get\" action=\"./records/allrecords\">\r\n"
				+ "        <button type=\"submit\" class=\"btn\" style=\"background-color:blue; margin-bottom:20px;\">\r\n"
				+ "            <i class=\"fa-solid fa-file-pen\"></i>\r\n"
				+ "            All Records\r\n"
				+ "            </button>\r\n"
				+ "             </form>\r\n"
				+ "       \r\n"
				+ "          <form method=\"get\" action=\"./records/pendingrecords\">\r\n"
				+ "        <button type=\"submit\" class=\"btn\" style=\"background-color:blue; margin-bottom:20px;\">\r\n"
				+ "            <i class=\"fa-solid fa-file-pen\"></i>\r\n"
				+ "            Pending Records\r\n"
				+ "            </button>\r\n"
				+ "            </form>\r\n"
				+ "          <form method=\"get\" action=\"./records/returnedrecords\">\r\n"
				+ "        <button type=\"submit\" class=\"btn\" style=\"background-color:blue; margin-bottom:20px;\">\r\n"
				+ "            <i class=\"fa-solid fa-file-pen\"></i>\r\n"
				+ "            Returned Records\r\n"
				+ "            </button>\r\n"
				+ "            </form>\r\n"
				+ "     \r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "  <script type=\"text/javascript\" src=\"https://d1tgh8fmlzexmh.cloudfront.net/ccbp-static-website/js/ccbp-ui-kit.js\"></script>\r\n"
				+ "</body>\r\n"
				+ "</html>"
				);
		
		
		
		
	}

	

}
